name: AssemblyScript HAL tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hal_tests:
    name: Test ${{ matrix.test }}
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        include:
        - test: spi
        - test: i2c
        - test: gpio

    steps:
    - uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache-dependency-path: package-lock.json

    # TODO: make this work alongside PRs to the spec and RT.
    # probably move tests for a given spec version to the runtime to simplify this
    - name: Fetch spec
      uses: actions/checkout@v2
      with:
        repository: embedded-wasm/spec
        path: spec

    - name: Fetch (latest) runtime
      run: |
        wget https://github.com/embedded-wasm/rt/releases/latest/download/wasm-embedded-rt-x86_64-unknown-linux-gnu.tgz
        tar -xvf wasm-embedded-rt-x86_64-unknown-linux-gnu.tgz

    - name: Install dependencies
      run: npm ci

    - name: Build ${{ matrix.test }} test
      run: |
        npm exec asc -- tests/test_${{ matrix.test }}.ts -o build/test-${{ matrix.test }}.wasm

    - name: Run ${{ matrix.test }} test
      run: |
        ./wasm-embedded-rt --mode mock --config spec/tests/${{ matrix.test }}.toml ./build/test-${{ matrix.test }}.wasm
  
